function hoursAgo(hours: number): string {
  return new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();
}

function daysAgo(days: number): string {
  return new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString();
}

export function paginate<T>(items: T[], page: number, limit: number): { items: T[]; total: number } {
  const start = (page - 1) * limit;
  return { items: items.slice(start, start + limit), total: items.length };
}

export async function liveOrMock<T>(request: () => Promise<T>, mock: T, isEmpty?: (data: T) => boolean): Promise<T> {
  try {
    const data = await request();
    if (isEmpty?.(data)) {
      return mock;
    }
    return data;
  } catch {
    return mock;
  }
}

export const MOCK_OVERVIEW = {
  totalUsers: 1284,
  kycPending: 37,
  activeTrips: 42,
  bookingsToday: 19,
};

export const MOCK_REVENUE = {
  platformFee: { allTime: 486250, thisMonth: 42890 },
  cancellationBonds: { allTime: 18600, thisMonth: 2100 },
  subscriptionRevenueActive: 96400,
};

export const MOCK_USERS = [
  {
    id: "usr_01",
    phone: "+919876501001",
    name: "Ananya Rao",
    role: "both",
    trust_score: 92,
    is_admin: true,
    is_active: true,
    aadhaar_verified: true,
    dl_verified: true,
    face_match_done: true,
    created_at: daysAgo(120),
  },
  {
    id: "usr_02",
    phone: "+919876501002",
    name: "Karthik Iyer",
    role: "driver",
    trust_score: 88,
    is_admin: false,
    is_active: true,
    aadhaar_verified: true,
    dl_verified: true,
    face_match_done: true,
    created_at: daysAgo(86),
  },
  {
    id: "usr_03",
    phone: "+919876501003",
    name: "Meera Nair",
    role: "passenger",
    trust_score: 81,
    is_admin: false,
    is_active: true,
    aadhaar_verified: true,
    dl_verified: false,
    face_match_done: true,
    created_at: daysAgo(44),
  },
  {
    id: "usr_04",
    phone: "+919876501004",
    name: "Vikram Shah",
    role: "driver",
    trust_score: 74,
    is_admin: false,
    is_active: true,
    aadhaar_verified: true,
    dl_verified: true,
    face_match_done: false,
    created_at: daysAgo(21),
  },
  {
    id: "usr_05",
    phone: "+919876501005",
    name: "Priya Menon",
    role: "passenger",
    trust_score: 69,
    is_admin: false,
    is_active: false,
    aadhaar_verified: false,
    dl_verified: false,
    face_match_done: false,
    created_at: daysAgo(12),
  },
  {
    id: "usr_06",
    phone: "+919876501006",
    name: "Arjun Patel",
    role: "both",
    trust_score: 95,
    is_admin: false,
    is_active: true,
    aadhaar_verified: true,
    dl_verified: true,
    face_match_done: true,
    created_at: daysAgo(200),
  },
  {
    id: "usr_07",
    phone: "+919876501007",
    name: "Sana Qureshi",
    role: "passenger",
    trust_score: 77,
    is_admin: false,
    is_active: true,
    aadhaar_verified: true,
    dl_verified: false,
    face_match_done: true,
    created_at: daysAgo(8),
  },
  {
    id: "usr_08",
    phone: "+919876501008",
    name: "Rahul Desai",
    role: "driver",
    trust_score: 61,
    is_admin: false,
    is_active: true,
    aadhaar_verified: true,
    dl_verified: true,
    face_match_done: true,
    created_at: daysAgo(3),
  },
];

export const MOCK_TRIPS = [
  {
    id: "trp_01",
    origin_name: "Krishnagiri",
    destination_name: "Bengaluru",
    departure_time: hoursAgo(-6),
    seats_total: 3,
    seats_available: 1,
    price_per_seat: 650,
    status: "active",
    trip_type: "outstation",
    is_women_only: false,
    users: { name: "Karthik Iyer", phone: "+919876501002" },
  },
  {
    id: "trp_02",
    origin_name: "Chennai",
    destination_name: "Pondicherry",
    departure_time: hoursAgo(-18),
    seats_total: 3,
    seats_available: 2,
    price_per_seat: 480,
    status: "active",
    trip_type: "outstation",
    is_women_only: true,
    users: { name: "Ananya Rao", phone: "+919876501001" },
  },
  {
    id: "trp_03",
    origin_name: "Hyderabad",
    destination_name: "Vijayawada",
    departure_time: hoursAgo(5),
    seats_total: 4,
    seats_available: 0,
    price_per_seat: 720,
    status: "in_progress",
    trip_type: "outstation",
    is_women_only: false,
    users: { name: "Arjun Patel", phone: "+919876501006" },
  },
  {
    id: "trp_04",
    origin_name: "Pune",
    destination_name: "Mumbai",
    departure_time: daysAgo(1),
    seats_total: 3,
    seats_available: 0,
    price_per_seat: 550,
    status: "completed",
    trip_type: "outstation",
    is_women_only: false,
    users: { name: "Vikram Shah", phone: "+919876501004" },
  },
  {
    id: "trp_05",
    origin_name: "Coimbatore",
    destination_name: "Madurai",
    departure_time: daysAgo(2),
    seats_total: 2,
    seats_available: 2,
    price_per_seat: 400,
    status: "cancelled",
    trip_type: "outstation",
    is_women_only: false,
    users: { name: "Rahul Desai", phone: "+919876501008" },
  },
  {
    id: "trp_06",
    origin_name: "Whitefield",
    destination_name: "Koramangala",
    departure_time: hoursAgo(-2),
    seats_total: 3,
    seats_available: 2,
    price_per_seat: 180,
    status: "active",
    trip_type: "local",
    is_women_only: false,
    users: { name: "Karthik Iyer", phone: "+919876501002" },
  },
  {
    id: "trp_07",
    origin_name: "Ahmedabad",
    destination_name: "Vadodara",
    departure_time: daysAgo(4),
    seats_total: 4,
    seats_available: 1,
    price_per_seat: 390,
    status: "completed",
    trip_type: "outstation",
    is_women_only: true,
    users: { name: "Ananya Rao", phone: "+919876501001" },
  },
  {
    id: "trp_08",
    origin_name: "Jaipur",
    destination_name: "Delhi",
    departure_time: hoursAgo(-30),
    seats_total: 3,
    seats_available: 1,
    price_per_seat: 890,
    status: "active",
    trip_type: "outstation",
    is_women_only: false,
    users: { name: "Arjun Patel", phone: "+919876501006" },
  },
];

export const MOCK_BOOKINGS = [
  {
    id: "bkg_01",
    seats_booked: 1,
    subtotal: 650,
    total_amount: 76,
    status: "confirmed",
    created_at: hoursAgo(3),
    trips: { origin_name: "Krishnagiri", destination_name: "Bengaluru", departure_time: hoursAgo(-6) },
  },
  {
    id: "bkg_02",
    seats_booked: 2,
    subtotal: 960,
    total_amount: 112,
    status: "pending",
    created_at: hoursAgo(1),
    trips: { origin_name: "Chennai", destination_name: "Pondicherry", departure_time: hoursAgo(-18) },
  },
  {
    id: "bkg_03",
    seats_booked: 1,
    subtotal: 720,
    total_amount: 84,
    status: "confirmed",
    created_at: hoursAgo(6),
    trips: { origin_name: "Hyderabad", destination_name: "Vijayawada", departure_time: hoursAgo(5) },
  },
  {
    id: "bkg_04",
    seats_booked: 1,
    subtotal: 550,
    total_amount: 64,
    status: "completed",
    created_at: daysAgo(1),
    trips: { origin_name: "Pune", destination_name: "Mumbai", departure_time: daysAgo(1) },
  },
  {
    id: "bkg_05",
    seats_booked: 1,
    subtotal: 400,
    total_amount: 47,
    status: "cancelled",
    created_at: daysAgo(2),
    trips: { origin_name: "Coimbatore", destination_name: "Madurai", departure_time: daysAgo(2) },
  },
  {
    id: "bkg_06",
    seats_booked: 1,
    subtotal: 180,
    total_amount: 21,
    status: "confirmed",
    created_at: hoursAgo(2),
    trips: { origin_name: "Whitefield", destination_name: "Koramangala", departure_time: hoursAgo(-2) },
  },
  {
    id: "bkg_07",
    seats_booked: 2,
    subtotal: 780,
    total_amount: 91,
    status: "completed",
    created_at: daysAgo(4),
    trips: { origin_name: "Ahmedabad", destination_name: "Vadodara", departure_time: daysAgo(4) },
  },
  {
    id: "bkg_08",
    seats_booked: 1,
    subtotal: 890,
    total_amount: 104,
    status: "pending",
    created_at: hoursAgo(4),
    trips: { origin_name: "Jaipur", destination_name: "Delhi", departure_time: hoursAgo(-30) },
  },
];

export const MOCK_PAYMENTS = [
  {
    id: "pay_01",
    amount: 76,
    service_fee: 64,
    type: "escrow",
    status: "captured",
    provider: "razorpay",
    booking_id: "bkg_01",
    created_at: hoursAgo(3),
    users: { name: "Meera Nair", phone: "+919876501003" },
  },
  {
    id: "pay_02",
    amount: 112,
    service_fee: 95,
    type: "escrow",
    status: "created",
    provider: "razorpay",
    created_at: hoursAgo(1),
    users: { name: "Sana Qureshi", phone: "+919876501007" },
  },
  {
    id: "pay_03",
    amount: 150,
    service_fee: 127,
    type: "cancellation_bond",
    status: "captured",
    provider: "razorpay",
    created_at: daysAgo(1),
    users: { name: "Rahul Desai", phone: "+919876501008" },
  },
  {
    id: "pay_04",
    amount: 84,
    service_fee: 71,
    type: "escrow",
    status: "captured",
    provider: "razorpay",
    created_at: hoursAgo(6),
    users: { name: "Priya Menon", phone: "+919876501005" },
  },
  {
    id: "pay_05",
    amount: 499,
    service_fee: 423,
    type: "escrow",
    status: "captured",
    provider: "razorpay",
    created_at: daysAgo(5),
    users: { name: "Karthik Iyer", phone: "+919876501002" },
  },
  {
    id: "pay_06",
    amount: 47,
    service_fee: 40,
    type: "escrow",
    status: "refunded",
    provider: "razorpay",
    created_at: daysAgo(2),
    users: { name: "Vikram Shah", phone: "+919876501004" },
  },
  {
    id: "pay_07",
    amount: 21,
    service_fee: 18,
    type: "escrow",
    status: "authorized",
    provider: "razorpay",
    created_at: hoursAgo(2),
    users: { name: "Meera Nair", phone: "+919876501003" },
  },
  {
    id: "pay_08",
    amount: 64,
    service_fee: 54,
    type: "escrow",
    status: "failed",
    provider: "razorpay",
    created_at: hoursAgo(9),
    users: { name: "Sana Qureshi", phone: "+919876501007" },
  },
];

export const MOCK_SUBSCRIPTIONS = [
  {
    id: "sub_01",
    plan_type: "driver_outstation",
    cadence: "monthly",
    amount_inr: 499,
    status: "active",
    expires_at: hoursAgo(-24 * 18),
    created_at: daysAgo(12),
    users: { name: "Karthik Iyer", phone: "+919876501002" },
  },
  {
    id: "sub_02",
    plan_type: "driver_local",
    cadence: "monthly",
    amount_inr: 199,
    status: "active",
    expires_at: hoursAgo(-24 * 9),
    created_at: daysAgo(21),
    users: { name: "Vikram Shah", phone: "+919876501004" },
  },
  {
    id: "sub_03",
    plan_type: "passenger",
    cadence: "monthly",
    amount_inr: 999,
    status: "active",
    expires_at: hoursAgo(-24 * 280),
    created_at: daysAgo(80),
    users: { name: "Meera Nair", phone: "+919876501003" },
  },
  {
    id: "sub_04",
    plan_type: "driver_outstation",
    cadence: "monthly",
    amount_inr: 499,
    status: "pending",
    expires_at: null,
    created_at: hoursAgo(6),
    users: { name: "Rahul Desai", phone: "+919876501008" },
  },
  {
    id: "sub_05",
    plan_type: "passenger",
    cadence: "monthly",
    amount_inr: 99,
    status: "expired",
    expires_at: daysAgo(4),
    created_at: daysAgo(34),
    users: { name: "Priya Menon", phone: "+919876501005" },
  },
  {
    id: "sub_06",
    plan_type: "driver_local",
    cadence: "monthly",
    amount_inr: 199,
    status: "cancelled",
    expires_at: daysAgo(10),
    created_at: daysAgo(40),
    users: { name: "Arjun Patel", phone: "+919876501006" },
  },
];

export const MOCK_RATINGS = [
  {
    id: "rt_01",
    stars: 5,
    comment: "On time and very courteous. Smooth highway drive.",
    tags: ["safe", "on_time"],
    created_at: hoursAgo(8),
    rater: { name: "Meera Nair", phone: "+919876501003" },
    ratee: { name: "Karthik Iyer", phone: "+919876501002" },
  },
  {
    id: "rt_02",
    stars: 4,
    comment: "Good ride. AC was a bit weak after Hosur.",
    tags: ["friendly"],
    created_at: daysAgo(1),
    rater: { name: "Sana Qureshi", phone: "+919876501007" },
    ratee: { name: "Arjun Patel", phone: "+919876501006" },
  },
  {
    id: "rt_03",
    stars: 2,
    comment: "Waited 20 minutes at pickup. Please be punctual.",
    tags: ["late"],
    created_at: daysAgo(2),
    rater: { name: "Priya Menon", phone: "+919876501005" },
    ratee: { name: "Vikram Shah", phone: "+919876501004" },
  },
  {
    id: "rt_04",
    stars: 5,
    comment: "Women-only trip felt completely safe.",
    tags: ["safe", "women_only"],
    created_at: daysAgo(4),
    rater: { name: "Sana Qureshi", phone: "+919876501007" },
    ratee: { name: "Ananya Rao", phone: "+919876501001" },
  },
  {
    id: "rt_05",
    stars: 3,
    comment: "Music was loud. Otherwise fine.",
    tags: ["needs_improvement"],
    created_at: daysAgo(5),
    rater: { name: "Rahul Desai", phone: "+919876501008" },
    ratee: { name: "Karthik Iyer", phone: "+919876501002" },
  },
  {
    id: "rt_06",
    stars: 1,
    comment: "Cancelled after I reached the pin.",
    tags: ["cancelled"],
    created_at: daysAgo(6),
    rater: { name: "Meera Nair", phone: "+919876501003" },
    ratee: { name: "Rahul Desai", phone: "+919876501008" },
  },
];

export const MOCK_SAFETY = [
  {
    id: "saf_01",
    event_type: "sos",
    severity: "critical",
    lat: 12.9716,
    lng: 77.5946,
    metadata: {},
    resolved: false,
    created_at: hoursAgo(1),
    user_id: "usr_03",
    users: { name: "Meera Nair", phone: "+919876501003" },
  },
  {
    id: "saf_02",
    event_type: "route_deviation",
    severity: "high",
    lat: 12.7409,
    lng: 77.8253,
    metadata: {},
    resolved: false,
    created_at: hoursAgo(4),
    user_id: "usr_02",
    users: { name: "Karthik Iyer", phone: "+919876501002" },
  },
  {
    id: "saf_03",
    event_type: "otp_fail",
    severity: "medium",
    lat: 13.0827,
    lng: 80.2707,
    metadata: {},
    resolved: false,
    created_at: hoursAgo(7),
    user_id: "usr_04",
    users: { name: "Vikram Shah", phone: "+919876501004" },
  },
  {
    id: "saf_04",
    event_type: "sos",
    severity: "critical",
    lat: 17.385,
    lng: 78.4867,
    metadata: {},
    resolved: true,
    created_at: daysAgo(1),
    user_id: "usr_07",
    users: { name: "Sana Qureshi", phone: "+919876501007" },
  },
  {
    id: "saf_05",
    event_type: "fraud_flag",
    severity: "high",
    lat: null,
    lng: null,
    metadata: {},
    resolved: false,
    created_at: daysAgo(2),
    user_id: "usr_05",
    users: { name: "Priya Menon", phone: "+919876501005" },
  },
  {
    id: "saf_06",
    event_type: "route_deviation",
    severity: "low",
    lat: 18.5204,
    lng: 73.8567,
    metadata: {},
    resolved: true,
    created_at: daysAgo(3),
    user_id: "usr_06",
    users: { name: "Arjun Patel", phone: "+919876501006" },
  },
];

export const MOCK_OPEN_SOS = MOCK_SAFETY.filter((event) => event.event_type === "sos" && !event.resolved);

export const MOCK_KYC = [
  {
    id: "kyc_01",
    user_id: "usr_03",
    document_type: "dl" as const,
    status: "pending" as const,
    storage_path: "usr_03/dl.jpg",
    created_at: hoursAgo(2),
    reviewed_at: null,
    review_note: null,
    users: { id: "usr_03", name: "Meera Nair", phone: "+919876501003", photo_url: null },
  },
  {
    id: "kyc_02",
    user_id: "usr_04",
    document_type: "selfie" as const,
    status: "pending" as const,
    storage_path: "usr_04/selfie.jpg",
    created_at: hoursAgo(5),
    reviewed_at: null,
    review_note: null,
    users: { id: "usr_04", name: "Vikram Shah", phone: "+919876501004", photo_url: null },
  },
  {
    id: "kyc_03",
    user_id: "usr_05",
    document_type: "aadhaar" as const,
    status: "pending" as const,
    storage_path: "usr_05/aadhaar.jpg",
    created_at: hoursAgo(8),
    reviewed_at: null,
    review_note: null,
    users: { id: "usr_05", name: "Priya Menon", phone: "+919876501005", photo_url: null },
  },
  {
    id: "kyc_04",
    user_id: "usr_07",
    document_type: "dl" as const,
    status: "pending" as const,
    storage_path: "usr_07/dl.jpg",
    created_at: hoursAgo(12),
    reviewed_at: null,
    review_note: null,
    users: { id: "usr_07", name: "Sana Qureshi", phone: "+919876501007", photo_url: null },
  },
  {
    id: "kyc_05",
    user_id: "usr_05",
    document_type: "selfie" as const,
    status: "pending" as const,
    storage_path: "usr_05/selfie.jpg",
    created_at: hoursAgo(9),
    reviewed_at: null,
    review_note: null,
    users: { id: "usr_05", name: "Priya Menon", phone: "+919876501005", photo_url: null },
  },
  {
    id: "kyc_06",
    user_id: "usr_02",
    document_type: "aadhaar" as const,
    status: "verified" as const,
    storage_path: "usr_02/aadhaar.jpg",
    created_at: daysAgo(20),
    reviewed_at: daysAgo(19),
    review_note: null,
    users: { id: "usr_02", name: "Karthik Iyer", phone: "+919876501002", photo_url: null },
  },
  {
    id: "kyc_07",
    user_id: "usr_08",
    document_type: "selfie" as const,
    status: "rejected" as const,
    storage_path: "usr_08/selfie.jpg",
    created_at: daysAgo(1),
    reviewed_at: hoursAgo(6),
    review_note: "Face not fully visible. Ask for a clearer selfie.",
    users: { id: "usr_08", name: "Rahul Desai", phone: "+919876501008", photo_url: null },
  },
  {
    id: "kyc_08",
    user_id: "usr_04",
    document_type: "aadhaar" as const,
    status: "failed" as const,
    storage_path: "usr_04/aadhaar.jpg",
    created_at: daysAgo(2),
    reviewed_at: null,
    review_note: null,
    users: { id: "usr_04", name: "Vikram Shah", phone: "+919876501004", photo_url: null },
  },
];

export const MOCK_VEHICLES = [
  {
    id: "veh_01",
    driver_id: "usr_02",
    make: "Hyundai",
    model: "Creta",
    color: "White",
    registration_number: "KA01AB1234",
    year: 2022,
    vehicle_type: "car",
    is_verified: true,
    created_at: daysAgo(80),
    users: { id: "usr_02", name: "Karthik Iyer", phone: "+919876501002" },
    driver_profile: { user_id: "usr_02", dl_number: "KA1234567890", cancellation_count: 1, reliability_score: 0.9, years_of_experience: 6 },
  },
  {
    id: "veh_02",
    driver_id: "usr_04",
    make: "Maruti",
    model: "Swift",
    color: "Grey",
    registration_number: "MH12CD7788",
    year: 2019,
    vehicle_type: "car",
    is_verified: false,
    created_at: daysAgo(12),
    users: { id: "usr_04", name: "Vikram Shah", phone: "+919876501004" },
    driver_profile: { user_id: "usr_04", dl_number: "MH0987654321", cancellation_count: 4, reliability_score: 0.6, years_of_experience: 3 },
  },
  {
    id: "veh_03",
    driver_id: "usr_06",
    make: "Honda",
    model: "Activa",
    color: "Blue",
    registration_number: "TS09EF4411",
    year: 2021,
    vehicle_type: "bike",
    is_verified: false,
    created_at: daysAgo(4),
    users: { id: "usr_06", name: "Arjun Patel", phone: "+919876501006" },
    driver_profile: { user_id: "usr_06", dl_number: "TS1122334455", cancellation_count: 0, reliability_score: 1, years_of_experience: 8 },
  },
  {
    id: "veh_04",
    driver_id: "usr_08",
    make: "Tata",
    model: "Nexon",
    color: "Black",
    registration_number: "TN07GH9900",
    year: 2023,
    vehicle_type: "car",
    is_verified: true,
    created_at: daysAgo(40),
    users: { id: "usr_08", name: "Rahul Desai", phone: "+919876501008" },
    driver_profile: { user_id: "usr_08", dl_number: "TN5566778899", cancellation_count: 2, reliability_score: 0.8, years_of_experience: 4 },
  },
];

export const MOCK_CONTACTS: Record<string, Array<{ id: string; name: string; phone: string; relationship: string }>> = {
  usr_03: [{ id: "ec_01", name: "Ravi Nair", phone: "+919876500111", relationship: "Father" }],
  usr_02: [{ id: "ec_02", name: "Lakshmi Iyer", phone: "+919876500222", relationship: "Spouse" }],
  usr_05: [{ id: "ec_03", name: "Anita Menon", phone: "+919876500333", relationship: "Sister" }],
};

